services:
  db:
    image: mariadb:11.7.1-noble-rc
    container_name: mariadb_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: dungeon_world
    networks:
      - internal_net
    volumes:
      - mariadb_data:/var/lib/mysql


  app:
    build: .     
    container_name: blazor_app
    restart: always
    volumes:
      - data_protection_keys:/var/protection-keys
    depends_on:
      - db
    environment:
      MariaDB__ConnString: "server=db;user=root;password=my-secret-pw;database=dungeon_world;"
      MariaDB__ServerVersion: "11.7.1"
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: false
      HUB_URL: http://localhost:8080
    networks:
      - internal_net


  nginx:
    image: nginx:1.26.3-alpine
    container_name: nginx_proxy
    restart: always
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Montando a configuração do Nginx
    ports:
      - "8085:80"  # Expondo apenas o Nginx
    networks:
      - external_net  # Nginx exposto ao host
      - internal_net  # Comunicação com a app

networks:
  internal_net:
    internal: true
  external_net:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
  data_protection_keys:
