// <auto-generated />
using System;
using DungeonWorldFIcha.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DungeonWorldFIcha.Migrations
{
    [DbContext(typeof(DungeonWorldContext))]
    [Migration("20250217132538_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DungeonWorldFIcha.Models.Habilidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Carisma")
                        .HasColumnType("int");

                    b.Property<int>("Constituicao")
                        .HasColumnType("int");

                    b.Property<int>("Destreza")
                        .HasColumnType("int");

                    b.Property<int>("Forca")
                        .HasColumnType("int");

                    b.Property<int>("Inteligencia")
                        .HasColumnType("int");

                    b.Property<int>("Sabedoria")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Habilidades");
                });

            modelBuilder.Entity("DungeonWorldFIcha.Models.Movimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("PersonagemId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Situacoes")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PersonagemId");

                    b.ToTable("Movimentos");
                });

            modelBuilder.Entity("DungeonWorldFIcha.Models.Personagem", b =>
                {
                    b.Property<Guid>("PersonagemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Armadura")
                        .HasColumnType("int");

                    b.Property<int>("DadoDano")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Equipamentos")
                        .HasColumnType("longtext");

                    b.Property<Guid>("HabilidadeId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Pv")
                        .HasColumnType("int");

                    b.HasKey("PersonagemId");

                    b.HasIndex("HabilidadeId");

                    b.ToTable("Personages");
                });

            modelBuilder.Entity("DungeonWorldFIcha.Models.Movimento", b =>
                {
                    b.HasOne("DungeonWorldFIcha.Models.Personagem", null)
                        .WithMany("Movimentos")
                        .HasForeignKey("PersonagemId");
                });

            modelBuilder.Entity("DungeonWorldFIcha.Models.Personagem", b =>
                {
                    b.HasOne("DungeonWorldFIcha.Models.Habilidade", "Habilidade")
                        .WithMany()
                        .HasForeignKey("HabilidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habilidade");
                });

            modelBuilder.Entity("DungeonWorldFIcha.Models.Personagem", b =>
                {
                    b.Navigation("Movimentos");
                });
#pragma warning restore 612, 618
        }
    }
}
